//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.42000
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="KPSPublicSoap", Namespace="http://tckimlik.nvi.gov.tr/WS")]
public partial class KPSPublic : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback TCKimlikNoDogrulaOperationCompleted;
    
    /// <remarks/>
    public KPSPublic() {
        this.Url = "https://tckimlik.nvi.gov.tr/Service/KPSPublic.asmx";
    }
    
    /// <remarks/>
    public event TCKimlikNoDogrulaCompletedEventHandler TCKimlikNoDogrulaCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tckimlik.nvi.gov.tr/WS/TCKimlikNoDogrula", RequestNamespace="http://tckimlik.nvi.gov.tr/WS", ResponseNamespace="http://tckimlik.nvi.gov.tr/WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool TCKimlikNoDogrula(long TCKimlikNo, string Ad, string Soyad, int DogumYili) {
        object[] results = this.Invoke("TCKimlikNoDogrula", new object[] {
                    TCKimlikNo,
                    Ad,
                    Soyad,
                    DogumYili});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void TCKimlikNoDogrulaAsync(long TCKimlikNo, string Ad, string Soyad, int DogumYili) {
        this.TCKimlikNoDogrulaAsync(TCKimlikNo, Ad, Soyad, DogumYili, null);
    }
    
    /// <remarks/>
    public void TCKimlikNoDogrulaAsync(long TCKimlikNo, string Ad, string Soyad, int DogumYili, object userState) {
        if ((this.TCKimlikNoDogrulaOperationCompleted == null)) {
            this.TCKimlikNoDogrulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTCKimlikNoDogrulaOperationCompleted);
        }
        this.InvokeAsync("TCKimlikNoDogrula", new object[] {
                    TCKimlikNo,
                    Ad,
                    Soyad,
                    DogumYili}, this.TCKimlikNoDogrulaOperationCompleted, userState);
    }
    
    private void OnTCKimlikNoDogrulaOperationCompleted(object arg) {
        if ((this.TCKimlikNoDogrulaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.TCKimlikNoDogrulaCompleted(this, new TCKimlikNoDogrulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void TCKimlikNoDogrulaCompletedEventHandler(object sender, TCKimlikNoDogrulaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TCKimlikNoDogrulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal TCKimlikNoDogrulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
